### ISSUE TITLE
Binaries in the repo.

### ISSUE THREAD

**Issue by avikantz** [mitcse/CSE-Labs#5]
Executable files must be removed from the repo.

**Comment by rahul-kumi** [comment]
I will do the clean up of the repo.

**Comment by rahul-kumi** [comment]
@avikantz , Do I remove the `.class` files too?

**Comment by avikantz** [comment]
@rahul-kumi Yes.

**Comment by rahul-kumi** [comment]
@avikantz , do I remove the `.scf` files too?

**Comment by mridulnagpal** [comment]
Hey i want  to contribute to this project can you tell me of something specific you want me to add to this project

**Comment by avikantz** [comment]
@rahul-kumi keep the .scf files for the output purposes.

**Comment by rahul-kumi** [comment]
@avikantz , then the raised PR #9 should suffice the need, I have left the `.scf` files intact!

**Comment by avikantz** [comment]
@mridulnagpal detailed description on contributions will be put up by tonight
