### ISSUE TITLE
Fixing 2-3 tree algorithm

### ISSUE THREAD

**Issue by avikantz** [mitcse/CSE-Labs#6]
There seems to be a problem with node splitting after insertion. Implement a preorder/postorder traversal to check.

https://github.com/mitcse/CSE-Labs/blob/master/ALG%20Lab/Transform%20and%20Conquer/Two%20Three/TwoThree.c

**Comment by rahul-kumi** [comment]
I will work on the issue!

**Comment by jiteshjha** [comment]
2-3 tree is never gonna happen :P

**Comment by avikantz** [comment]
:'(
