### ISSUE TITLE
SJF scheduling algorithm fix.

### ISSUE THREAD

**Issue by avikantz** [mitcse/CSE-Labs#7]
SJF process scheduling algorithm implemented in [sjf.c](https://github.com/mitcse/CSE-Labs/blob/master/OS%20Lab/CPU%20Scheduling/sjf.c) is giving negative wait time for input set:

| Arrival time        | Burst time           |
| ------------ |:-------------:| 
| 0 | 8 | 
| 4 | 5 | 
| 3 | 2 | 
| 2 | 1 |

**Comment by anuraagbaishya** [comment]
Is this preemptive or non preemptive? In either case, I have code that gives proper answer to this case. I'll add the files.
